#!/usr/bin/env bash
set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

set -u

export GST_DEBUG_DUMP_DOT_DIR=/opt/dots


export pipeline=$(cat ./wip.gstp | tr "\n" " ")
echo pipeline=$pipeline

gst-launch-1.0 -v -e $pipeline
