version: '3'

services:
  pythia-demo:
    image: rmclabs-io/pythia-demo
    build:
      context: .
      dockerfile: pythia_demo/Dockerfile
    volumes:
      - /home/rmclabs/RMCLabs/webrtcdemo/db:/db
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/rmclabs/RMCLabs/webrtcdemo/debug/vids:/opt/vids
    network_mode: "host"
    runtime: nvidia
    restart: always
    environment:
      - DISPLAY=:0 
      - PYTHONUNBUFFERED=1
 
  # sendrecv-gst:
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   network_mode: "host"
  #   build: ./sendrecv/gst
  #   # ports:
  #   #   - 8000:8000
  #   runtime: nvidia
  #   restart: always
  #   environment:
  #     - DISPLAY=:0 

  # sendrecv-js:
  #   build: ./sendrecv/js
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - signalling

  flask-front:
    build:
      context: .
      dockerfile: front/Dockerfile
    network_mode: "host"
    volumes:
      - /home/rmclabs/RMCLabs/webrtcdemo/db:/db
      - /home/rmclabs/RMCLabs/webrtcdemo/debug:/videos
    # ports:
    #   - 8080:8888
    depends_on:
      - signalling
    environment:
      - PYTHONUNBUFFERED=1

  signalling:
    build: ./signalling
    network_mode: "host"
    # ports:
    #   - 9443:8443
