version: '3'

services:
  backend:
    volumes:
        - ./debug/dots:/opt/dots
    environment:
        - GST_DEBUG_DUMP_DOT_DIR=/opt/
        - GST_DEBUG_LOG_LEVEL=
        - LOGLEVEL=info
        