version: '3'

services:

  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf 
  
  pythia-demo:
    image: rmclabs-io/pythia-demo
    build:
      context: .
      dockerfile: pythia_demo/Dockerfile
    volumes:
      - $DB_LOCAL_PATH:$DB_REMOTE_PATH
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $VIDEO_LOCAL_PATH:$VIDEO_REMOTE_PATH
    network_mode: "host"
    runtime: nvidia
    restart: always
    environment:
      - DISPLAY=:0 
      - PYTHONUNBUFFERED=1
 

  motion-heatmap:
    image: rmclabs-io/motion-heatmap
    build:
      context: .
      dockerfile: motion/Dockerfile
    volumes:
      - /home/rmclabs/RMCLabs/webrtcdemo/motion:/motion
      - $DB_LOCAL_PATH:$DB_REMOTE_PATH
      - $HEATMAP_LOCAL_PATH:$HEATMAP_REMOTE_PATH
      - $VIDEO_LOCAL_PATH:$VIDEO_REMOTE_PATH
    network_mode: "host"
    runtime: nvidia
    restart: always
    environment:
      - DISPLAY=:0
      - PYTHONUNBUFFERED=1
    depends_on:
      - signalling

  flask-front:
    build:
      context: .
      dockerfile: front/Dockerfile
    network_mode: "host"
    volumes:
      - $DB_LOCAL_PATH:$DB_REMOTE_PATH
    # ports:
    #   - 8080:8888
    depends_on:
      - signalling
    environment:
      - PYTHONUNBUFFERED=1

  signalling:
    build: ./signalling
    network_mode: "host"
    # ports:
    #   - 9443:8443
