version: '3'


services:

  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf 
      - ./signalling/cert.pem:/certs/cert.pem
      - ./signalling/key.pem:/certs/key.pem

  signalling:
    image: rmclabs-io/ventanas-signalling
    build: ./signalling
    network_mode: "host"
    depends_on:
      - nginx
    environment:
      - SIGNALLING_HOST=0.0.0.0
      - SIGNALLING_PORT=7003
    

  backend:
    image: rmclabs-io/ventanas-backend_deepstream
    build:
      context: .
      dockerfile: backend_deepstream/Dockerfile
    volumes:
      - ./db:/db
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./videos:/videos
      - ./signalling/cert.pem:/certs/cert.pem
      - ./signalling/key.pem:/certs/key.pem
    network_mode: "host"
    runtime: nvidia
    restart: always
    environment:
      - DISPLAY=:0 
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=7001
 
  frontend:
    image: rmclabs-io/ventanas-app_flask
    build:
      context: .
      dockerfile: frontend_flask/Dockerfile
    network_mode: "host"
    runtime: nvidia
    volumes:
      - ./db:/db
      - ./videos:/videos
      - ./signalling/cert.pem:/certs/cert.pem
      - ./signalling/key.pem:/certs/key.pem
    depends_on:
      - nginx
      - signalling
      - backend
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=7002
      - CERTS_PATH=/certs/
